# number of marker set descriptions
int32 n_marker_sets

# number of rigid body descriptions
int32 n_rigid_bodies

# number of skeleton descriptions
int32 n_skeletons

# number of force plate descriptions
int32 n_force_plates

# number of device descriptions
int32 n_devices

# number of camera descriptions
int32 n_cameras

# MarkerSetDescription
MarkerSetDescription[] marker_set_descriptions

# RigidBodyDescription
RigidBodyDescription[] rigid_body_descriptions

# SkeletonDescription
SkeletonDescription[] skeleton_descriptions

# ForcePlateDescription
ForcePlateDescription[] force_plate_descriptions

# DeviceDescription
DeviceDescription[] device_descriptions

# CameraDescription
CameraDescription[] camera_descriptions
